import os, glob, json
from src.story import generate_story
from src.voice import generate_voice
from src.video import create_video

def main():
    os.makedirs("output/images", exist_ok=True)
    os.makedirs("output/final", exist_ok=True)
    
    print("1. Generating story...")
    title, script, description = generate_story()
    print(f"Title: {title}")
    
    # Save story
    with open("output/story.json", "w", encoding="utf-8") as f:
        json.dump({"title": title, "script": script, "description": description}, f, ensure_ascii=False, indent=2)
    
    print("2. Generating voice...")
    audio_path = generate_voice(script, "output/voice.mp3")
    print(f"Audio: {audio_path}")
    
    print("3. Finding images...")
    # Images already generated by your old flow? If not, create simple text images as fallback
    image_paths = sorted(glob.glob("output/images/*.jpg"))
    if not image_paths:
        print("No images found, creating placeholder images")
        from PIL import Image, ImageDraw, ImageFont
        try:
            RESAMPLE = Image.Resampling.LANCZOS
        except:
            RESAMPLE = Image.LANCZOS
        for i in range(3):
            img = Image.new('RGB', (1080, 1920), color=(20, 20, 40))
            d = ImageDraw.Draw(img)
            d.text((100, 900), title[:30], fill=(255,255,255))
            path = f"output/images/scene_{i}.jpg"
            img.save(path)
            image_paths.append(path)
    
    print(f"Images: {image_paths}")
    
    print("4. Creating video...")
    final_video = create_video(image_paths, audio_path, "output/final/final_video.mp4")
    
    print("5. Uploading to YouTube...")
    try:
        from src.youtube import upload_to_youtube
        upload_to_youtube(final_video, title, description)
    except Exception as e:
        print(f"YouTube upload skipped/failed: {e}")
    
    print(f"Done: {final_video}")
    return final_video

if __name__ == "__main__":
    main()
